### ISSUE TITLE
Some cards with "facedown" and some ranked classes render oddly

### ISSUE THREAD

**Issue by mooniker** [jyaus/css-playing-cards#1]
I noticed that the demo for facedown cards goes like this:

``` html
<div class="card card-hearts card-a card-facedown"><span></span></div>
```

but I've found that giving facedown card elements a ranked class (e.g. "card-a") causes them to render irregularly. In particular, the 10's render with two suit symbols and the 9's, 7's, and 5's also render with a suit symbol on their facedown side.

``` html
<figure class="card card-hearts card-10 card-facedown"><span></span></figure>
<figure class="card card-facedown card-spades card-9"><span></span></figure>
```

renders with some weirdness but if the rank and suit classes are removed, they render as one would expect.

**Comment by jyaus** [comment]
Wow, totally missed this message when you sent it! Sorry about the delay.

Good catch; fixed. Thanks!
